### ISSUE TITLE
Functions to retrieve the variables from the MediaPlaylist struct

### ISSUE THREAD

**Issue by benhughesdon** [ssttevee/m3u8#1]
Hello,

I am trying to use your repo to retrieve the Duration and other variables from MediaSegment instances of MediaPlaylist.

The playlist file is successfully decoded, and the values for each variable can be returned. I want to be able to select the specific variables such as those I have mentioned. The team I am working in will then use the values from these variables for video selection and retrieval, with the aid of a database. 

Regards,

Ben Hughes

**Comment by ssttevee** [comment]
Hi Ben, is [`MediaSegment.Duration`](https://github.com/ssttevee/m3u8/blob/a6f26d92b5cec19afbc85b40dab6009dfaef7e9d/segment.go#L22) not sufficient?

**Comment by benhughesdon** [comment]
> Hi Ben, is [`MediaSegment.Duration`](https://github.com/ssttevee/m3u8/blob/a6f26d92b5cec19afbc85b40dab6009dfaef7e9d/segment.go#L22) not sufficient?

Hi Steve,

I am trying to retrieve the Segments from the plist variable that is populated with a decoded Playlist, as has been generated from your Parse from a Stream example:

Parse a playlist from a stream:

```
f, err := os.Open("playlist.m3u8")
if err != nil {
	panic(err)
}

plist, err := m3u8.NewDecoder(f).Decode()
if err != nil {
	panic(err)
}

switch plist.(type) {
case *m3u8.MasterPlaylist:
	fmt.Println("I am a master playlist!")
case *m3u8.MediaPlaylist:
	fmt.Println("I am a media playlist!")
}

```

This is a screenshot from the Debugger in VS Code. It shows the new Playlist plist, and its variable values that I need to retrieve.

![image](https://user-images.githubusercontent.com/64783608/94420495-2697ff00-017c-11eb-84a7-afed421e080b.png)

**Comment by benhughesdon** [comment]
It would be fabulous if you could add (to the page https://github.com/ssttevee/m3u8)  an example of how to specifically retrieve the values of the variables from the decoded playlist.

I think that what has been holding me back is my limited experience with pointers.

**Comment by ssttevee** [comment]
If you're only working with media playlists, you can just forego the type switch and just use a type cast:

```
mediaPlaylist, ok := plist.(*m3u8.MediaPlaylist)
if !ok {
    panic("not a media playlist")
}

for i, segment := mediaPlaylist.Segments {
    fmt.Printf("segment %d is %s\n", i, segment.Duration)
}
```

**Comment by benhughesdon** [comment]
Thank you very much Steve! :)
I have now been able to achieve my goal with this library.
